import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { auth } from "~/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import { Navbar } from "~/app/_components/navbar";

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="min-h-screen flex flex-col bg-slate-50 antialiased">
        <TRPCReactProvider>
          <Navbar isLoggedIn={!!session?.user} />
          <div className="flex-1 flex flex-col">
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
